services:
  db:
    image: mysql:9.1.0
    container_name: adventure-xp-db
    restart: always
    environment:
      MYSQL_DATABASE: adventure_xp
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: